### ISSUE TITLE
More liberal license?

### ISSUE THREAD

**Issue by niansa** [gwizdz/asyncpq#1]
Hey, I'd like to use this in my open source project (https://gitlab.com/niansa/cdlpp-db; extension of https://gitlab.com/niansa/cdlpp), but your license ("all right reserved") forbids it and I'd rather not submodule it either.

**Comment by gwizdz** [comment]
Feel free to use it if you like.
In a few days I will update code to the proper license (probably Boost Software License, didn't decide yet).
I will also commit some improvements to the code.

**Comment by niansa** [comment]
Okay cool thanks!
